# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 743)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("#MainWindow\n"
"{\n"
"    background:rgb(255, 250, 229);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"}\n"
"\n"
"* { \n"
"    font: 30 15pt \"微软雅黑 Light\";\n"
"}\n"
"\n"
"QPushButton \n"
"{\n"
"    background:rgb(40, 40, 40);\n"
"    border-radius:15px;\n"
"    color:rgb(255, 251, 234);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 640, 480))
        self.label.setMinimumSize(QtCore.QSize(640, 480))
        self.label.setMaximumSize(QtCore.QSize(640, 480))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/gif/g1.gif"))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 520, 640, 91))
        self.frame.setStyleSheet("QFrame{\n"
"    background:rgb(32, 24, 32);\n"
"}\n"
"* {\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tips = QtWidgets.QLabel(self.frame)
        self.tips.setGeometry(QtCore.QRect(366, 20, 241, 51))
        self.tips.setStyleSheet("* {\n"
"    font: 25pt \"方正粗黑宋简体\";\n"
"}\n"
"")
        self.tips.setObjectName("tips")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(130, 25, 211, 41))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("* {\n"
"    font: 25pt \"方正粗黑宋简体\";\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.Emoji = QtWidgets.QLabel(self.centralwidget)
        self.Emoji.setGeometry(QtCore.QRect(650, 50, 70, 70))
        self.Emoji.setMinimumSize(QtCore.QSize(70, 70))
        self.Emoji.setMaximumSize(QtCore.QSize(70, 70))
        self.Emoji.setText("")
        self.Emoji.setPixmap(QtGui.QPixmap(":/png/happy-p.png"))
        self.Emoji.setObjectName("Emoji")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 630, 641, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 22)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_off = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_off.sizePolicy().hasHeightForWidth())
        self.b_off.setSizePolicy(sizePolicy)
        self.b_off.setMinimumSize(QtCore.QSize(150, 50))
        self.b_off.setStyleSheet("QPushButton:hover \n"
"{\n"
"    color: red;\n"
"\n"
" }")
        self.b_off.setObjectName("b_off")
        self.horizontalLayout.addWidget(self.b_off)
        self.b_start = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_start.sizePolicy().hasHeightForWidth())
        self.b_start.setSizePolicy(sizePolicy)
        self.b_start.setMinimumSize(QtCore.QSize(150, 50))
        self.b_start.setStyleSheet("QPushButton:hover \n"
"{\n"
" color: rgb(36, 158, 29);\n"
"\n"
" }")
        self.b_start.setObjectName("b_start")
        self.horizontalLayout.addWidget(self.b_start)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "表情检测程序"))
        self.tips.setText(_translate("MainWindow", "单击开始"))
        self.label_2.setText(_translate("MainWindow", "检测状态："))
        self.b_off.setText(_translate("MainWindow", "停止"))
        self.b_start.setText(_translate("MainWindow", "开始"))
import qt.pic_rc
